package com.example.administrator.policemap.dataEngin.localDataService.database.greenDaoDataBase;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.policemap.dataEngin.localDataService.database.greenDaoDataBase.entity.PolicePeople;
import com.example.administrator.policemap.dataEngin.localDataService.database.greenDaoDataBase.entity.UnitBase;
import com.example.administrator.policemap.dataEngin.localDataService.database.greenDaoDataBase.entity.MissionInfo;
import com.example.administrator.policemap.dataEngin.localDataService.database.greenDaoDataBase.entity.DBMap;

import com.example.administrator.policemap.dataEngin.localDataService.database.greenDaoDataBase.PolicePeopleDao;
import com.example.administrator.policemap.dataEngin.localDataService.database.greenDaoDataBase.UnitBaseDao;
import com.example.administrator.policemap.dataEngin.localDataService.database.greenDaoDataBase.MissionInfoDao;
import com.example.administrator.policemap.dataEngin.localDataService.database.greenDaoDataBase.DBMapDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig policePeopleDaoConfig;
    private final DaoConfig unitBaseDaoConfig;
    private final DaoConfig missionInfoDaoConfig;
    private final DaoConfig dBMapDaoConfig;

    private final PolicePeopleDao policePeopleDao;
    private final UnitBaseDao unitBaseDao;
    private final MissionInfoDao missionInfoDao;
    private final DBMapDao dBMapDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        policePeopleDaoConfig = daoConfigMap.get(PolicePeopleDao.class).clone();
        policePeopleDaoConfig.initIdentityScope(type);

        unitBaseDaoConfig = daoConfigMap.get(UnitBaseDao.class).clone();
        unitBaseDaoConfig.initIdentityScope(type);

        missionInfoDaoConfig = daoConfigMap.get(MissionInfoDao.class).clone();
        missionInfoDaoConfig.initIdentityScope(type);

        dBMapDaoConfig = daoConfigMap.get(DBMapDao.class).clone();
        dBMapDaoConfig.initIdentityScope(type);

        policePeopleDao = new PolicePeopleDao(policePeopleDaoConfig, this);
        unitBaseDao = new UnitBaseDao(unitBaseDaoConfig, this);
        missionInfoDao = new MissionInfoDao(missionInfoDaoConfig, this);
        dBMapDao = new DBMapDao(dBMapDaoConfig, this);

        registerDao(PolicePeople.class, policePeopleDao);
        registerDao(UnitBase.class, unitBaseDao);
        registerDao(MissionInfo.class, missionInfoDao);
        registerDao(DBMap.class, dBMapDao);
    }
    
    public void clear() {
        policePeopleDaoConfig.getIdentityScope().clear();
        unitBaseDaoConfig.getIdentityScope().clear();
        missionInfoDaoConfig.getIdentityScope().clear();
        dBMapDaoConfig.getIdentityScope().clear();
    }

    public PolicePeopleDao getPolicePeopleDao() {
        return policePeopleDao;
    }

    public UnitBaseDao getUnitBaseDao() {
        return unitBaseDao;
    }

    public MissionInfoDao getMissionInfoDao() {
        return missionInfoDao;
    }

    public DBMapDao getDBMapDao() {
        return dBMapDao;
    }

}
