package com.example.administrator.policemap.dataEngin.localDataService.database.greenDaoDataBase;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.administrator.policemap.dataEngin.localDataService.database.greenDaoDataBase.entity.PolicePeople;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "POLICE_PEOPLE".
*/
public class PolicePeopleDao extends AbstractDao<PolicePeople, Long> {

    public static final String TABLENAME = "POLICE_PEOPLE";

    /**
     * Properties of entity PolicePeople.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "id");
        public final static Property PoliceName = new Property(1, String.class, "policeName", false, "police_name");
        public final static Property PolicePhone = new Property(2, String.class, "policePhone", false, "police_phone");
        public final static Property UnitId = new Property(3, int.class, "unitId", false, "unit_id");
        public final static Property CreateTime = new Property(4, java.util.Date.class, "createTime", false, "create_time");
    };


    public PolicePeopleDao(DaoConfig config) {
        super(config);
    }
    
    public PolicePeopleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"POLICE_PEOPLE\" (" + //
                "\"id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"police_name\" TEXT NOT NULL ," + // 1: policeName
                "\"police_phone\" TEXT NOT NULL ," + // 2: policePhone
                "\"unit_id\" INTEGER NOT NULL ," + // 3: unitId
                "\"create_time\" INTEGER NOT NULL );"); // 4: createTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"POLICE_PEOPLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PolicePeople entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getPoliceName());
        stmt.bindString(3, entity.getPolicePhone());
        stmt.bindLong(4, entity.getUnitId());
        stmt.bindLong(5, entity.getCreateTime().getTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PolicePeople entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getPoliceName());
        stmt.bindString(3, entity.getPolicePhone());
        stmt.bindLong(4, entity.getUnitId());
        stmt.bindLong(5, entity.getCreateTime().getTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public PolicePeople readEntity(Cursor cursor, int offset) {
        PolicePeople entity = new PolicePeople( //
            cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // policeName
            cursor.getString(offset + 2), // policePhone
            cursor.getInt(offset + 3), // unitId
            new java.util.Date(cursor.getLong(offset + 4)) // createTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PolicePeople entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setPoliceName(cursor.getString(offset + 1));
        entity.setPolicePhone(cursor.getString(offset + 2));
        entity.setUnitId(cursor.getInt(offset + 3));
        entity.setCreateTime(new java.util.Date(cursor.getLong(offset + 4)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PolicePeople entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PolicePeople entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
